export default {
  CONFIG_REQUEST: 'config/CONFIG_REQUEST',
  CONFIG_REQUEST_SUCCESS: 'config/CONFIG_REQUEST_SUCCESS',
  CONFIG_REQUEST_ERROR: 'config/CONFIG_REQUEST_ERROR',
  CONFIG_MODIFICA_CAMPO: 'config/CONFIG_MODIFICA_CAMPO',
};
