export const Types = {
  UPDATE_PHARMACY_STATUS: '@pharmacy/UPDATE_PHARMACY_STATUS',
  UPDATE_PHARMACY_STATUS_SUCCESS: '@pharmacy/UPDATE_PHARMACY_STATUS_SUCCESS',
  UPDATE_PHARMACY_STATUS_ERROR: '@pharmacy/UPDATE_PHARMACY_STATUS_ERROR',
  CLEAR_PHARMACY_RESPONSE: '@pharmacy/CLEAR_PHARMACY_RESPONSE',

  FETCH_PRODUCT: '@product/FETCH_PRODUCT',
  FETCH_PRODUCT_SUCCESS: '@product/FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_ERROR: '@product/FETCH_PRODUCT_ERROR',

  UPDATE_PRODUCT_STATUS: '@product/UPDATE_PRODUCT_STATUS',
  UPDATE_PRODUCT_STATUS_SUCCESS: '@product/UPDATE_PRODUCT_STATUS_SUCCESS',
  UPDATE_PRODUCT_STATUS_ERROR: '@product/UPDATE_PRODUCT_STATUS_ERROR',

  ORDER_GROUP_REQUEST: '@order/ORDER_GROUP_REQUEST',
  ORDER_GROUP_SUCCESS: '@order/ORDER_GROUP_SUCCESS',
  ORDER_GROUP_FAILED: '@order/ORDER_GROUP_FAILED',

  ORDER_LIST_STATUS_REQUEST: '@order/ORDER_LIST_STATUS_REQUEST',
  ORDER_LIST_STATUS_SUCCESS: '@order/ORDER_LIST_STATUS_SUCCESS',
  ORDER_LIST_STATUS_FAILED: '@order/ORDER_LIST_STATUS_FAILED',
};
